// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tamp.Findings.Data;

#nullable disable

namespace Tamp.Findings.Data.Migrations
{
    [DbContext(typeof(FindingsDbContext))]
    [Migration("20260519124422_AddSbom")]
    partial class AddSbom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentFlavor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "Name")
                        .IsUnique();

                    b.ToTable("ComponentFlavors");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BuildId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FlavorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PullRequestRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VersionString")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CommitSha");

                    b.HasIndex("FlavorId");

                    b.HasIndex("ComponentId", "FlavorId", "VersionString")
                        .IsUnique();

                    b.ToTable("ComponentVersions");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Scanner")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Snippet")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Scanner");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("ComponentVersionId", "Hash")
                        .IsUnique();

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ProjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role", "ClientId", "ProjectId", "ComponentId")
                        .IsUnique();

                    b.ToTable("ProjectRoleAssignments");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CurrentReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LatestReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("License")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Purl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("SbomSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SbomSnapshotId", "Purl")
                        .IsUnique();

                    b.ToTable("SbomComponents");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SbomSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildComponentId");

                    b.HasIndex("ParentComponentId");

                    b.HasIndex("SbomSnapshotId", "ParentComponentId", "ChildComponentId")
                        .IsUnique();

                    b.ToTable("SbomDependencies");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SpecVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ToolName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId")
                        .IsUnique();

                    b.ToTable("SbomSnapshots");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Suppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RuleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FindingId");

                    b.HasIndex("RuleId");

                    b.ToTable("Suppressions");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Vulnerability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvisoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FixedInVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("SbomComponentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Severity");

                    b.HasIndex("SbomComponentId", "AdvisoryId")
                        .IsUnique();

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Component", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Project", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentFlavor", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Component", "Component")
                        .WithMany("Flavors")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentVersion", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Component", "Component")
                        .WithMany("Versions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentFlavor", "Flavor")
                        .WithMany()
                        .HasForeignKey("FlavorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Component");

                    b.Navigation("Flavor");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Finding", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany("Findings")
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Project", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomComponent", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.SbomSnapshot", "SbomSnapshot")
                        .WithMany("Components")
                        .HasForeignKey("SbomSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SbomSnapshot");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomDependency", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.SbomComponent", null)
                        .WithMany()
                        .HasForeignKey("ChildComponentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.SbomComponent", null)
                        .WithMany()
                        .HasForeignKey("ParentComponentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.SbomSnapshot", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("SbomSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomSnapshot", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Vulnerability", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.SbomComponent", "SbomComponent")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("SbomComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SbomComponent");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Component", b =>
                {
                    b.Navigation("Flavors");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentVersion", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Project", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomComponent", b =>
                {
                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomSnapshot", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Dependencies");
                });
#pragma warning restore 612, 618
        }
    }
}
