// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tamp.Findings.Data;
using Tamp.Findings.Domain.Entities;
using Tamp.Findings.Domain.Risk;

#nullable disable

namespace Tamp.Findings.Data.Migrations
{
    [DbContext(typeof(FindingsDbContext))]
    [Migration("20260823173109_Tfnd8_PaidComponents")]
    partial class Tfnd8_PaidComponents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.AttestationSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DocumentJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneratedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RiskPolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RiskPolicyName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SignedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CommitSha", "GeneratedAt");

                    b.ToTable("AttestationSnapshots");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.AuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ActorLogin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ActorRole")
                        .HasColumnType("integer");

                    b.Property<bool>("ActorWasAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectKind")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("Class", "At");

                    b.HasIndex("ClientId", "ProjectId", "At");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RiskPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RiskPolicyId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Component", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentFlavor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "Name")
                        .IsUnique();

                    b.ToTable("ComponentFlavors");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BranchName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("BuildId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FlavorId")
                        .HasColumnType("uuid");

                    b.Property<string>("PullRequestRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("VersionString")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("CommitSha");

                    b.HasIndex("FlavorId");

                    b.HasIndex("ComponentId", "FlavorId", "VersionString")
                        .IsUnique();

                    b.ToTable("ComponentVersions");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BranchCoverage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CoverageModuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CoverageSourceFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoveredBranches")
                        .HasColumnType("integer");

                    b.Property<int>("CoveredSequences")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<double>("SequenceCoverage")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalBranches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSequences")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("UnvisitedLines")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("VisitedLines")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("CoverageSourceFileId");

                    b.HasIndex("CoverageModuleId", "FullName", "CoverageSourceFileId")
                        .IsUnique();

                    b.ToTable("CoverageClasses");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BranchCoverage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CoverageReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoveredSequences")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<double>("SequenceCoverage")
                        .HasColumnType("double precision");

                    b.Property<int>("TotalSequences")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CoverageReportId", "Name")
                        .IsUnique();

                    b.ToTable("CoverageModules");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("BranchCoverage")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoveredBranches")
                        .HasColumnType("integer");

                    b.Property<int>("CoveredSequences")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("SequenceCoverage")
                        .HasColumnType("double precision");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalBranches")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSequences")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId")
                        .IsUnique();

                    b.ToTable("CoverageReports");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageSourceFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbsolutePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("CoverageReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoverageReportId", "RelativePath")
                        .IsUnique();

                    b.ToTable("CoverageSourceFiles");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Line")
                        .HasColumnType("integer");

                    b.Property<string>("Purl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Scanner")
                        .HasColumnType("integer");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Snippet")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubCategory")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Scanner");

                    b.HasIndex("Severity");

                    b.HasIndex("Status");

                    b.HasIndex("ComponentVersionId", "Hash")
                        .IsUnique();

                    b.ToTable("Findings");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.HostAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CanonicalHost")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Alias")
                        .IsUnique();

                    b.ToTable("HostAliases");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.IdentityProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastSignInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedClientSecret")
                        .HasColumnType("text");

                    b.Property<bool>("RequireMfa")
                        .HasColumnType("boolean");

                    b.Property<string>("Scheme")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Scopes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Scheme")
                        .IsUnique();

                    b.ToTable("IdentityProviders");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.IngestToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("IngestTokens");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.InstanceSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("AllowedEmailDomains")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("BuildRetentionDays")
                        .HasColumnType("integer");

                    b.Property<bool>("EnforceSeparationOfDuties")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("ExpectedScanners")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int?>("FindingRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("GitHubAppId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GitHubAppPrivateKeyProtected")
                        .HasColumnType("text");

                    b.Property<string>("GitHubCheckName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("GitHubChecksEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("InstanceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("McpEnabled")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<List<string>>("MfaRequiredRoles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("SessionLifetimeHours")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpFrom")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("InstanceSettings");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.KevAdvisory", b =>
                {
                    b.Property<string>("CveId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("KnownRansomwareCampaignUse")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Product")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RequiredAction")
                        .HasColumnType("text");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("VendorProject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("VulnerabilityName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("CveId");

                    b.HasIndex("DueDate");

                    b.HasIndex("KnownRansomwareCampaignUse");

                    b.ToTable("KevAdvisories");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.McpToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("ClientId", "ProjectId", "ComponentId");

                    b.ToTable("McpTokens");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.PaidComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AnnualCostPerSeat")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("CostAsOf")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Ecosystem")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseModel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("PackagePrefix")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PricingUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Product")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("SupportEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Ecosystem", "PackagePrefix")
                        .IsUnique();

                    b.ToTable("PaidComponents");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.PendingApproval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedByLogin")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("DecidedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DecisionNote")
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByLogin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("WorkflowInstanceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("State", "AssignedToUserId");

                    b.HasIndex("SubjectKind", "SubjectId", "State");

                    b.ToTable("PendingApprovals");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.PoamItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActualCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<string>("LinkedFindingIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MitigationPlan")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ResourcesRequired")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("ScheduledCompletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WeaknessDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClosedAt");

                    b.HasIndex("ProjectId", "Status", "ScheduledCompletionDate");

                    b.ToTable("PoamItems");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<ProjectGatesConfig>("GatesConfig")
                        .HasColumnType("jsonb");

                    b.Property<string>("GitHubRepository")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("RiskPolicyId")
                        .HasColumnType("uuid");

                    b.Property<string>("VdpContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("VdpPolicyUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("VdpReportingFormUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("RiskPolicyId");

                    b.HasIndex("ClientId", "Name")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ProjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("SodConflict")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role", "ClientId", "ProjectId", "ComponentId")
                        .IsUnique();

                    b.ToTable("ProjectRoleAssignments");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.RiskPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<RiskPolicyConfig>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("RiskPolicies");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CurrentReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Dictionary<string, string>>("Hashes")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("LatestReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LatestVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("License")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Purl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("SbomSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SbomSnapshotId", "Purl")
                        .IsUnique();

                    b.ToTable("SbomComponents");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentComponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SbomSnapshotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildComponentId");

                    b.HasIndex("ParentComponentId");

                    b.HasIndex("SbomSnapshotId", "ParentComponentId", "ChildComponentId")
                        .IsUnique();

                    b.ToTable("SbomDependencies");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<List<Dictionary<string, string>>>("MetadataTools")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Dictionary<string, object>>("ProvenanceJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProvenanceType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ProvenanceUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SpecVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ToolName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId")
                        .IsUnique();

                    b.ToTable("SbomSnapshots");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ScanRunReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("FindingsCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("Scanner")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("ToolName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId", "Scanner")
                        .IsUnique();

                    b.ToTable("ScanRunReceipts");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Suppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ComponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByRole")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("RuleId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("FindingId");

                    b.HasIndex("RuleId");

                    b.HasIndex("ClientId", "ProjectId");

                    b.ToTable("Suppressions");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestCaseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestSuiteResultId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestSuiteResultId", "Name");

                    b.ToTable("TestCaseResults");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestRunReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ComponentVersionId")
                        .HasColumnType("uuid");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("InconclusiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PassedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ToolVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ComponentVersionId")
                        .IsUnique();

                    b.ToTable("TestRunReports");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestSuiteResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer");

                    b.Property<int>("InconclusiveCount")
                        .HasColumnType("integer");

                    b.Property<int>("PassedCount")
                        .HasColumnType("integer");

                    b.Property<int>("SkippedCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestRunReportId")
                        .HasColumnType("uuid");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TestRunReportId", "ClassName")
                        .IsUnique();

                    b.ToTable("TestSuiteResults");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalScheme")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long?>("GitHubUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("GitHubUserId")
                        .IsUnique()
                        .HasFilter("\"GitHubUserId\" IS NOT NULL");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("ExternalScheme", "ExternalSubject")
                        .IsUnique()
                        .HasFilter("\"ExternalSubject\" IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.VexStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvisoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImpactStatement")
                        .HasColumnType("text");

                    b.Property<int?>("Justification")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("ResponseReferenceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RetiredAt");

                    b.HasIndex("ProjectId", "AdvisoryId", "Purl");

                    b.ToTable("VexStatements");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Vulnerability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvisoryId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("CvssScore")
                        .HasColumnType("double precision");

                    b.Property<string>("CvssVector")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FixedInVersion")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ReferenceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("SbomComponentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("Severity");

                    b.HasIndex("SbomComponentId", "AdvisoryId")
                        .IsUnique();

                    b.ToTable("Vulnerabilities");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Client", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.RiskPolicy", null)
                        .WithMany()
                        .HasForeignKey("RiskPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Component", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Project", "Project")
                        .WithMany("Components")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentFlavor", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Component", "Component")
                        .WithMany("Flavors")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentVersion", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Component", "Component")
                        .WithMany("Versions")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentFlavor", "Flavor")
                        .WithMany()
                        .HasForeignKey("FlavorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Component");

                    b.Navigation("Flavor");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageClass", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.CoverageModule", "Module")
                        .WithMany("Classes")
                        .HasForeignKey("CoverageModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.CoverageSourceFile", "SourceFile")
                        .WithMany("Classes")
                        .HasForeignKey("CoverageSourceFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("SourceFile");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageModule", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.CoverageReport", "Report")
                        .WithMany("Modules")
                        .HasForeignKey("CoverageReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageReport", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageSourceFile", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.CoverageReport", "Report")
                        .WithMany("SourceFiles")
                        .HasForeignKey("CoverageReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Finding", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany("Findings")
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.PoamItem", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Project", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.RiskPolicy", null)
                        .WithMany()
                        .HasForeignKey("RiskPolicyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomComponent", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.SbomSnapshot", "SbomSnapshot")
                        .WithMany("Components")
                        .HasForeignKey("SbomSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SbomSnapshot");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomDependency", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.SbomComponent", null)
                        .WithMany()
                        .HasForeignKey("ChildComponentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.SbomComponent", null)
                        .WithMany()
                        .HasForeignKey("ParentComponentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tamp.Findings.Domain.Entities.SbomSnapshot", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("SbomSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomSnapshot", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ScanRunReceipt", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestCaseResult", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.TestSuiteResult", "Suite")
                        .WithMany("Cases")
                        .HasForeignKey("TestSuiteResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suite");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestRunReport", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.ComponentVersion", "ComponentVersion")
                        .WithMany()
                        .HasForeignKey("ComponentVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentVersion");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestSuiteResult", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.TestRunReport", "Report")
                        .WithMany("Suites")
                        .HasForeignKey("TestRunReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.VexStatement", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Vulnerability", b =>
                {
                    b.HasOne("Tamp.Findings.Domain.Entities.SbomComponent", "SbomComponent")
                        .WithMany("Vulnerabilities")
                        .HasForeignKey("SbomComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SbomComponent");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Component", b =>
                {
                    b.Navigation("Flavors");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.ComponentVersion", b =>
                {
                    b.Navigation("Findings");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageModule", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageReport", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("SourceFiles");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.CoverageSourceFile", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.Project", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomComponent", b =>
                {
                    b.Navigation("Vulnerabilities");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.SbomSnapshot", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestRunReport", b =>
                {
                    b.Navigation("Suites");
                });

            modelBuilder.Entity("Tamp.Findings.Domain.Entities.TestSuiteResult", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
